/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef MACADDRESS_AUTODEFS_H
#define MACADDRESS_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_MACADDRESS_NAME "MacAddress"
#define S3E_EXT_MACADDRESS_HASH 0x8a30853c

#include "s3eEdk.h"

#define MACADDRESSGLOBALS ((MacAddressGlobals*)s3eEdkGlobalsGet(S3E_EXT_MACADDRESS_HASH))
#endif /* !MACADDRESS_AUTODEFS_H */
