/*
 * Copyright (C) 2001-2012 Ideaworks3D Ltd.
 * All Rights Reserved.
 *
 * This document is protected by copyright, and contains information
 * proprietary to Ideaworks Labs.
 * This file consists of source code released by Ideaworks Labs under
 * the terms of the accompanying End User License Agreement (EULA).
 * Please do not use this program/source code before you have read the
 * EULA and have agreed to be bound by its terms.
 */
/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef S3E_EXT_MACADDRESS_H
#define S3E_EXT_MACADDRESS_H

/**
 * @addtogroup s3egroup
 * @{
 */

/**
 * @defgroup edkMacAddressapigroup Mac Address Extension API Reference
 *
 * This extension allows an application to display a native message box.
 *
 * This is an example extension supplied with the EDK. It is included to
 * demonstrate the implementation of a basic cross-platform extension and
 * is not intended for use in commercial applications.
 *
 * @{
 */

#include <s3eTypes.h>
// \cond HIDDEN_DEFINES
S3E_BEGIN_C_DECL
// \endcond

/**
 * Returns S3E_TRUE if the MacAddress extension is available.
 */
s3eBool MacAddressAvailable();

/**
 * Displays a modal message box with specified title and text.
 *
 * @par Required Header Files
 * MacAddress.h
 */
uint64 get_MacAddressAsNumber();

const char * get_MacAddressAsString();

S3E_END_C_DECL

/** @} */
/** @} */

#endif /* !S3E_EXT_MACADDRESS_H */
